# Profile information
name: SKYRIVUS
title: skyrivus - Free Jekyll Theme
description: > # this means to ignore newlines until "baseurl:"
  skyrivus 一个前端工程师的个人博客
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://skyrivus.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
